GET http://localhost:3000
###
POST http://localhost:3000/waifu
Content-Type: application/json

{
    "nickname": "alors1",
    "firstname": "alors2",
    "lastname": "alors3",
    "age": 12,
    "img": "alors5",
    "manga": "alors6",
    "firstIdea": null,
    "random": "alors"
}
###
POST http://localhost:3000/waifu
Content-Type: application/json

{
    "nickname": "alors1",
    "firstname": "alors2",
    "lastname": "alors3",
    "age": "feafe",
    "img": "alors5",
    "manga": "alors6",
    "firstIdea": "alors7",
    "random": "alors"
}
###
GET http://localhost:3000/waifu
###
DELETE http://localhost:3000/waifu/gage
###
GET http://localhost:3000/waifu
###
GET http://localhost:3000/waifu/2
###
PUT http://localhost:3000/waifu/7
Content-Type: application/json

{
    "nickname": "alors32",
    "random": "llll"
}
###
POST http://localhost:3000/user
Content-Type: application/json

{
    "userName": "username",
    "tag": "alors7",
    "grade": "grade",
    "random": "alors"
}
###
GET http://localhost:3000/user
###
PUT http://localhost:3000/user/2
Content-Type: application/json

{
    "userName": "changedName",
    "uselessName": "oiza'heg",
    "tag": "tag changed"
}
###
GET http://localhost:3000/user/2
###
DELETE http://localhost:3000/user/1
###
GET http://localhost:3000/user/tag/alors7
###
POST http://localhost:3000/waifu/1/points/-5